baseURL = "https://crbgc.org/"
title = "The Common & Recent Bogey Golf Club"

[languages.en]
locale = "en_US"
label = "English"
weight = 1

enableRobotsTXT = true
disableKinds = ["taxonomy", "term", "rss"]

[markup.tableOfContents]
startLevel = 2
endLevel = 3
